env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier

settings:
  import/resolver:
    typescript: {}

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - '@typescript-eslint'
  - sort-destructure-keys
  - unused-imports

rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never

  # eslint
  arrow-body-style: error
  curly: error
  no-restricted-imports:
    - error
    - '@emotion/styled'
    - '@mui/material'
    - next/router
  no-unused-vars: off
  padding-line-between-statements:
    - error
    - blankLine: always
      prev: '*'
      next: return
  sort-imports:
    - error
    - ignoreCase: true
      ignoreDeclarationSort: true

  # @typescript-eslint/eslint-plugin
  '@typescript-eslint/consistent-type-definitions':
    - error
    - type
  '@typescript-eslint/member-ordering':
    - error
    - typeLiterals:
        order: alphabetically-case-insensitive
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  '@typescript-eslint/sort-type-union-intersection-members': error

  # eslint-plugin-import
  import/newline-after-import:
    - error
  import/no-named-as-default-member:
    - off
  import/order:
    - error
    - alphabetize:
        caseInsensitive: true
        order: asc
      groups:
        - builtin
        - external
        - internal
        - unknown
        - parent
        - sibling
        - index
        - object
        - type
      newlines-between: always

  # eslint-plugin-sort-destructure-keys
  sort-destructure-keys/sort-destructure-keys:
    - error
    - caseSensitive: false

  # eslint-plugin-unused-imports
  unused-imports/no-unused-imports: error
  unused-imports/no-unused-vars:
    - error
    - args: after-used
      argsIgnorePattern: ^_
      vars: all
      varsIgnorePattern: ^_

overrides:
  - files: '*.js'
    rules:
      # @typescript-eslint/eslint-plugin
      '@typescript-eslint/no-var-requires': off

  - files:
      - '*.ts'
      - '*.tsx'
    rules:
      # @typescript-eslint/eslint-plugin
      '@typescript-eslint/naming-convention':
        - error
        - selector: typeAlias
          format: null
          custom:
            regex: '^([A-Z]|_Assert)[^_]*$'
            match: true
